## Numerical measurements of centre of mass
Let's use the computer to find the centre of mass of each plastic piece. For that, we need two python modules. One is called numpy and it contains functions to deal with numerical data in python. The matplotlib module provides lots of tools to display data in python.

In [1]:
import matplotlib.pyplot as plt
import numpy as np

# this is to make sure figures pop out as a separate window:
%matplotlib

# loading standard colour maps
from matplotlib import cm 

Using matplotlib backend: MacOSX


The code snippet below will prompt you for the filename of your scan. Make sure it is in the working directory! 
 Run the code cell below, and at the prompt,
type in the image filename for one of your pieces. For example, if
your piece is labelled `Q2`, you should type in `Q2` (or the full path to the file if is not in the working directory) in response to the question: `Name of image file?`.

In [3]:
fname = input('Name of image file?')
F = plt.imread(fname+'.png')

Name of image file?2


The following script reads plots the scanned figures.  The image file is read with the `imread()` function and is converted into a NumPy array named `F`. The `imshow` function is used to display the array as a greyscale image using axes with equal scaling.

In [4]:
fig, ax = plt.subplots()
implot = ax.imshow(F, cmap=cm.gray, aspect='equal')
plt.show()

You should see the piece displayed in white on a black background in the figure.  The axes are in pixels, and since no figure is complete with axis labels:

In [5]:
ax.set_xlabel('horizontal distance (in pixels)')
ax.set_ylabel('vertical distance (in pixels)')

Text(0, 0.5, 'vertical distance (in pixels)')

`F` is
simply a (large) table of numbers whose entries consist of zeros
(black) and ones (white). To examine the contents of
an array, type its name in a code cell.

In [12]:
print(F)
F.shape

[[0.49411765 0.5647059  0.6431373  ... 0.8980392  0.8901961  0.92156863]
 [0.57254905 0.6156863  0.654902   ... 0.8980392  0.8901961  0.92156863]
 [0.60784316 0.627451   0.6509804  ... 0.8980392  0.8901961  0.92156863]
 ...
 [0.12941177 0.26666668 0.32156864 ... 0.07843138 0.07058824 0.10196079]
 [0.14901961 0.21568628 0.59607846 ... 0.12156863 0.05098039 0.04313726]
 [0.09803922 0.12941177 0.39607844 ... 0.05098039 0.05490196 0.08627451]]


(2338, 1653)

We started this lab with explaining how in case of discrete masses, the centre $\bf{R}$ obeys:
\begin{equation}
    \sum_{i = 1}^n m_i\left(\mathbf{r}_i-\mathbf{R}\right) = 0 . 
\end{equation}

If the mass distribution is continuous with the density $\rho(\bf{r})$ within a solid $Q$, then the integral of the weighted position coordinates of the points in this volume relative to the center of mass R over the volume V is zero, that is
\begin{equation} 
   \iiint \limits _{Q}\rho (\mathbf {r} )(\mathbf {r} -\mathbf {R} )dV=0.
\end{equation}

Solving for the coordinates $\bf{R}$, we get
\begin{equation}
  \mathbf {R} ={\frac {1}{M}}\iiint \limits _{Q}\rho (\mathbf {r} )\mathbf {r} dV,
\end{equation}
where M is the total mass in the volume. 

If the density is constant, then
\begin{equation}
  \mathbf {R} ={\frac {1}{V}}\iiint \limits _{Q}\mathbf {r} dV,
\end{equation}
where V is the total volume. 

That is for 3-dimensional objects, but our plastic shapes are only 2-dimensional. In that case, the centre of mass of a plane object $S$ of uniform density involves not volumes $V$, but areas $A$:

$\mathbf{R} = (\bar{x},\bar{y})$,
where

\begin{eqnarray*}
\bar{x} = \frac{\int_Sx\, dA}{\int_SdA} ~~~~ \textrm{and} ~~~~
\bar{y} = \frac{\int_Sy\, dA}{\int_SdA} \, .
\end{eqnarray*}

We calculate each integral in the usual way, i.e., by

**(a)** dividing the set $S$ into small pieces,

**(b)** evaluating the quantity to the right of the $\int$ sign on each of the pieces, and

**(c)** adding these up.

In the denominators, the integral of $dA$ just yields the total area of the object.

Write a function definition

`def area(shape, res):`

which returns the area in **square millimetres**,
when `shape` is an array of zeros and ones and `res` is
the resolution of the scan in **dots per inch**. You can then use the function by typing
`area(F,100)` to display the area of the piece. (3 points)

**Hint**:
Each pixel (dot) in the scan has a fixed area which you can calculate.
You may find the `sum` function useful.
If `M = array([[1,2,3],[4,5,6]])` is a 2D array, then `sum(M,0)` is a 1D array formed by adding the rows, yielding `array([5,7,9])`,
while `sum(M,1)` is a 1D array formed by adding the columns, yielding `array([6,15])`; 
`sum(M)` adds both ways to give 21.
    

In [7]:
def area(shape,res):
    return np.sum(shape)*(25.4/res)**2
area(F,100)

227758.10899900002

For the integral $\int_Sx\, dA$, we again divide the set $S$ into small pieces.
For each small piece, we calculate $x\, dA$ which is the product
of the $x$ coordinate and the area of the piece.
If the piece is small enough, the $x$ coordinate can be
taken anywhere within the piece.


When we use a scanner, the pixels are small square regions which are ideal
candidates for the small pieces into which $S$ is to be divided.
Each pixel is an entry in the array `F`. The column number may be
regarded as the $x$ coordinate, and the row number as the $y$ coordinate.
Using the normal convention for array indices, this is written as
`F(y,x)` where the integer `y` is the row index and `x` is the column
index. In Python, array indices start at 0, and so `F(0,0)` is at the top left of the array.

Let us consider calculating $\int_Sx\, dA$ for an array with three rows and four columns.
In the table below, each `F(y,x)` is either one or zero, depending whether or not
the pixel belongs to the set $S$:

\begin{bmatrix}
\texttt{F(0,0)} & \texttt{F(0,1)} & \texttt{F(0,2)} & \texttt{F(0,3)}\\
\texttt{F(1,0)} & \texttt{F(1,1)} & \texttt{F(1,2)} & \texttt{F(1,3)}\\
\texttt{F(2,0)} & \texttt{F(2,1)} & \texttt{F(2,2)} & \texttt{F(2,3)}
\end{bmatrix}

Each pixel has an $x$ value associated with it, which is equal to the column (second) index.
We can multiply every `F(y,x)` by `x` to obtain the new table

\begin{bmatrix}
\texttt{0*F(0,0)} & \texttt{1*F(0,1)} & \texttt{2*F(0,2)} & \texttt{3*F(0,3)}\\
\texttt{0*F(1,0)} & \texttt{1*F(1,1)} & \texttt{2*F(1,2)} & \texttt{3*F(1,3)}\\
\texttt{0*F(2,0)} & \texttt{1*F(2,1)} & \texttt{2*F(2,2)} & \texttt{3*F(2,3)}
\end{bmatrix}

Remembering that each of the entries in this table is either zero
(if the pixel is not in $S$) or is equal to the value of $x$ for that pixel,
make sure that you can convince yourself that the value of $\int_Sx\, dA$ is the
**sum of all elements** in this table multiplied by the area of a single pixel. 

#### Q7 (5 points)
Use these ideas to complete the `cofm` function below that finds the centre of mass
of an array "a" consisting of zeros and ones. Notice that we do not need to know
the resolution in this case, because the area of a pixel appears in both the integrals in the
numerator and denominator, so that the area units cancel. The position of the centre of mass is
calculated in units of **pixels**.  The NumPy `arange` function is similar to the built-in Python `range`, but returns an array. 

**Note:** The inner dimensions of matrices must match in order to be multiplied together (e.g. a 2x2 matrix can be multiplied with a 2x4 matrix, but not a 4x2 matrix.  The `newaxis` object can be used to expand the dimensions of an array/matrix by one unit-length dimension. Evaluate the following cell as an example of how `newaxis` is used to change the dimensionality of an array.

In [8]:
a = np.array([5,4,3])
print(a)
print(a[:,np.newaxis])

def cofm(shape, area):
    return shape * area

x = np.arange(1653)
y = np.arange(2338)
y = y[:,np.newaxis]

print(cofm(F, x))
cofm(F, y)

[5 4 3]
[[5]
 [4]
 [3]]
[[0.00000000e+00 5.64705908e-01 1.28627455e+00 ... 1.48176472e+03
  1.46971374e+03 1.52243138e+03]
 [0.00000000e+00 6.15686297e-01 1.30980396e+00 ... 1.48176472e+03
  1.46971374e+03 1.52243138e+03]
 [0.00000000e+00 6.27451003e-01 1.30196083e+00 ... 1.48176472e+03
  1.46971374e+03 1.52243138e+03]
 ...
 [0.00000000e+00 2.66666681e-01 6.43137276e-01 ... 1.29411769e+02
  1.16541182e+02 1.68439218e+02]
 [0.00000000e+00 2.15686277e-01 1.19215691e+00 ... 2.00588236e+02
  8.41686286e+01 7.12627470e+01]
 [0.00000000e+00 1.29411772e-01 7.92156875e-01 ... 8.41176482e+01
  9.06431380e+01 1.42525494e+02]]


array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.72549045e-01, 6.15686297e-01, 6.54901981e-01, ...,
        8.98039222e-01, 8.90196085e-01, 9.21568632e-01],
       [1.21568632e+00, 1.25490201e+00, 1.30196083e+00, ...,
        1.79607844e+00, 1.78039217e+00, 1.84313726e+00],
       ...,
       [3.02176487e+02, 6.22666699e+02, 7.50862770e+02, ...,
        1.83137261e+02, 1.64823537e+02, 2.38078435e+02],
       [3.48109818e+02, 5.03843142e+02, 1.39243927e+03, ...,
        2.83984314e+02, 1.19090198e+02, 1.00768630e+02],
       [2.29117651e+02, 3.02435311e+02, 9.25635309e+02, ...,
        1.19141178e+02, 1.28305883e+02, 2.01623535e+02]])

In [11]:
print(x.shape)
y.shape

(1653,)


(2338, 1)

#### Q8 (5 pts) 
If we now enter

`xcm, ycm = cofm(F)`

the coordinates of the centre of mass returned from `cofm` are placed in `xcm` and `ycm`. 
Record the coordinates of the centre of mass (xcm and ycm) for each of the pieces of plastic using the scans and code you created.

In [9]:
xcm = cofm(F, x)
print(xcm)

ycm = cofm(F, y)
ycm

[[0.00000000e+00 5.64705908e-01 1.28627455e+00 ... 1.48176472e+03
  1.46971374e+03 1.52243138e+03]
 [0.00000000e+00 6.15686297e-01 1.30980396e+00 ... 1.48176472e+03
  1.46971374e+03 1.52243138e+03]
 [0.00000000e+00 6.27451003e-01 1.30196083e+00 ... 1.48176472e+03
  1.46971374e+03 1.52243138e+03]
 ...
 [0.00000000e+00 2.66666681e-01 6.43137276e-01 ... 1.29411769e+02
  1.16541182e+02 1.68439218e+02]
 [0.00000000e+00 2.15686277e-01 1.19215691e+00 ... 2.00588236e+02
  8.41686286e+01 7.12627470e+01]
 [0.00000000e+00 1.29411772e-01 7.92156875e-01 ... 8.41176482e+01
  9.06431380e+01 1.42525494e+02]]


array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.72549045e-01, 6.15686297e-01, 6.54901981e-01, ...,
        8.98039222e-01, 8.90196085e-01, 9.21568632e-01],
       [1.21568632e+00, 1.25490201e+00, 1.30196083e+00, ...,
        1.79607844e+00, 1.78039217e+00, 1.84313726e+00],
       ...,
       [3.02176487e+02, 6.22666699e+02, 7.50862770e+02, ...,
        1.83137261e+02, 1.64823537e+02, 2.38078435e+02],
       [3.48109818e+02, 5.03843142e+02, 1.39243927e+03, ...,
        2.83984314e+02, 1.19090198e+02, 1.00768630e+02],
       [2.29117651e+02, 3.02435311e+02, 9.25635309e+02, ...,
        1.19141178e+02, 1.28305883e+02, 2.01623535e+02]])